baseURL: "https://andrew.cullis.dev/"
title: Andrew Cullis
paginate: 5
theme: PaperModX

params:
    env: production
    title: Andrew Cullis
    description: "My personal website"

    DateFormat: "January, 2006"
    defaultTheme: light

    minify:
      disableXML: true
      minifyOutput: true

    cover:
      linkFullImages: false
      responsiveImages: true

    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowPostNavLinks: true

    label:
        icon: "/favicon.ico"
        text: "Andrew Cullis"

    homeInfoParams:
        Title: Hi, I'm Andrew 👋
        Content: Welcome to my portfolio! 🚀

    socialIcons:
        - name: github
          url: "https://github.com/Andy9oo"
        - name: linkedin
          url: "https://linkedin.com/in/andrew-cullis"
        - name: email
          url: "mailto:andrew@cullis.dev"

pluralizeListTitles: false

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
    main:
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 1
        - identifier: experience
          name: Experience
          url: /experience/
          weight: 2
        - identifier: education
          name: Education
          url: /education/
          weight: 3
        - identifier: skills
          name: Skills
          url: /skills/
          weight: 4
