baseURL: "https://cullis.dev/"
title: Andrew Cullis
paginate: 5
theme: PaperMod

params:
    env: production
    title: Andrew Cullis
    description: "My personal website"

    DateFormat: "January, 2006"
    defaultTheme: dark

    cover:
      linkFullImages: false
      responsiveImages: false

    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true

    label:
        icon: "/favicon.ico"
        text: "Andrew Cullis"

    homeInfoParams:
        Title: "Hi, I'm Andrew \U0001F44B"
        Content: Welcome to my website

    socialIcons:
        - name: github
          url: "https://github.com/Andy9oo"
        - name: linkedin
          url: "https://linkedin.com/in/andrew-cullis"
        - name: email
          url: "mailto:andrew@cullis.dev"

pluralizeListTitles: false

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
    main:
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 10
        - identifier: experience
          name: Experience
          url: /experience/
          weight: 20
        - identifier: education
          name: Education
          url: /education/
          weight: 30
        - identifier: skills
          name: Skills
          url: /skills/
          weight: 40
